# Generated by Django 5.0.2 on 2024-02-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_added',
        ),
    ]
